defaults.org=lcf-dev
defaults.project=profpay-wallet
auth.token=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
